"""V1.5 public-facing copy. Stable codes stay independent of UI language."""

LANGUAGES = ["English", "Español", "繁體中文", "簡體中文", "한국어"]

# Columns: English, Spanish, Traditional Chinese, Simplified Chinese, Korean.
ROWS = {
    "modules": ["Feature shortcuts", "Accesos a funciones", "功能入口", "功能入口", "기능 바로가기"],
    "home": ["Home", "Inicio", "回到首頁", "回到首页", "홈"],
    "continue_chat": ["Continue asking questions", "Seguir preguntando", "繼續提問", "继续提问", "계속 질문하기"],
    "guided_prompt": ["Using the information I provided, explain directions worth exploring and compare the relevant Medicare options, including trade-offs and items to confirm. Offer guidance for discussion, not an enrollment or switching decision.", "Con la información proporcionada, explique opciones de Medicare para explorar, sus diferencias, limitaciones y puntos por confirmar. Ofrezca orientación para conversar, no una decisión de inscripción o cambio.", "請根據我提供的情況，說明值得了解的方向，並比較相關 Medicare 選項的差異、限制與待確認事項。請提供討論建議，不替我決定投保或更換方案。", "请根据我提供的情况，说明值得了解的方向，并比较相关 Medicare 选项的差异、限制与待确认事项。请提供讨论建议，不替我决定投保或更换方案。", "제공한 상황을 바탕으로 알아볼 Medicare 선택지와 차이점, 제약 및 확인 사항을 비교해 주세요. 가입이나 변경 결정 대신 논의할 방향을 안내해 주세요."],
    "zip_lookup": ["Don't know your ZIP Code? Look it up at USPS ↗", "¿No sabe su código postal? Consúltelo en USPS ↗", "不知道 ZIP Code？到 USPS 查詢 ↗", "不知道 ZIP Code？到 USPS 查询 ↗", "우편번호를 모르시나요? USPS에서 조회하기 ↗"],
    "new_tab": ["Opens in a new tab; your answers stay here.", "Se abre en otra pestaña; sus respuestas se conservan aquí.", "另開分頁查詢，這裡填寫的內容會保留。", "另开分页查询，这里填写的内容会保留。", "새 탭에서 열리며 입력한 답변은 이 페이지에 유지됩니다."],
    "why": ["Why these directions may help", "Por qué considerar estas opciones", "為什麼可以考慮這些方向", "为什么可以考虑这些方向", "이 방향을 고려할 이유"],
    "watch": ["What still needs checking", "Qué falta por confirmar", "還需要確認的事項", "还需要确认的事项", "더 확인할 사항"],
    "next_steps": ["Three things to discuss or verify", "Tres puntos para conversar o verificar", "可以進一步討論或確認的三件事", "可以进一步讨论或确认的三件事", "논의하거나 확인할 세 가지"],
    "saved_language": ["This summary stays in the language used when it was prepared.", "Este resumen conserva el idioma en que se preparó.", "摘要保留產生時的語言，切換介面語言不會重新產生內容。", "摘要保留生成时的语言，切换界面语言不会重新生成内容。", "요약은 작성 당시의 언어로 유지됩니다."],
    "tagline": ["Your Medicare guide, one step at a time", "Su guía de Medicare, paso a paso", "一步一步了解您的 Medicare 選擇", "一步一步了解您的 Medicare 选择", "한 단계씩 알아보는 Medicare 안내"],
    "who": ["Who are you exploring for?", "¿Para quién busca información?", "您想為誰了解 Medicare？", "您想为谁了解 Medicare？", "누구를 위해 알아보시나요?"],
    "self": ["For myself", "Para mí", "為自己查詢", "为自己查询", "나 자신"],
    "family": ["Helping a parent or spouse", "Para un familiar", "協助家人", "协助家人", "부모님 또는 배우자 돕기"],
    "intent": ["What would you like help with today?", "¿En qué podemos ayudarle hoy?", "今天想先了解什麼？", "今天想先了解什么？", "오늘 어떤 도움이 필요하신가요?"],
    "explore": ["Explore my Medicare options", "Explorar mis opciones de Medicare", "一步一步探索適合的方向", "一步一步探索适合的方向", "Medicare 선택지 알아보기"],
    "question": ["I have a Medicare question", "Tengo una pregunta sobre Medicare", "我有一個 Medicare 問題", "我有一个 Medicare 问题", "Medicare에 대해 질문하기"],
    "start_unsure": ["I'm not sure where to start", "No sé por dónde empezar", "我不知道從哪裡開始", "我不知道从哪里开始", "어디서 시작할지 모르겠어요"],
    "journey": ["What are you looking to do?", "¿Qué desea hacer?", "您目前想了解哪個方向？", "您目前想了解哪个方向？", "어떤 내용을 알아보고 싶으신가요?"],
    "first": ["First-time Medicare enrollment", "Inscribirme en Medicare por primera vez", "第一次申請 Medicare，或即將滿 65 歲", "第一次申请 Medicare，或即将满 65 岁", "Medicare 첫 가입 또는 65세를 앞두고 있어요"],
    "review": ["Review my current Medicare coverage", "Revisar mi cobertura actual de Medicare", "已有 Medicare，想檢視目前的保障", "已有 Medicare，想查看目前的保障", "현재 Medicare 보장 검토하기"],
    "unknown": ["I'm not sure", "No estoy seguro/a", "我不確定", "我不确定", "잘 모르겠어요"],
    "back": ["← Back", "← Volver", "← 回上一步", "← 回上一步", "← 이전"],
    "next": ["Next →", "Siguiente →", "下一步 →", "下一步 →", "다음 →"],
    "intro": ["Let's understand your situation, one step at a time. Allow about 3–5 minutes. It's fine to be unsure or leave optional details blank.", "Conozcamos su situación paso a paso. Reserve unos 3–5 minutos. Puede indicar que no está seguro/a o dejar los datos opcionales en blanco.", "我們先了解您的狀況，約需 3–5 分鐘，一步一步帶您確認。不確定也沒關係，選填資料可以先留白。", "我们先了解您的状况，约需 3–5 分钟，一步一步带您确认。不确定也没关系，选填资料可以先留白。", "약 3–5분 동안 상황을 한 단계씩 알아볼게요. 잘 모르거나 선택 항목을 비워 두셔도 괜찮아요."],
    "progress": ["Step {step} of {total}", "Paso {step} de {total}", "第 {step} 步，共 {total} 步", "第 {step} 步，共 {total} 步", "{total}단계 중 {step}단계"],
    "coverage": ["Which best describes the current coverage?", "¿Cuál describe mejor la cobertura actual?", "目前的保障較接近哪一種？", "目前的保障较接近哪一种？", "현재 보장은 어떤 상태인가요?"],
    "original_medicare": ["Original Medicare", "Medicare Original", "Original Medicare（原始 Medicare）", "Original Medicare（原始 Medicare）", "Original Medicare"],
    "medicare_advantage": ["Medicare Advantage", "Medicare Advantage", "Medicare Advantage（優勢計畫）", "Medicare Advantage（优势计划）", "Medicare Advantage"],
    "employer_coverage": ["Employer or retiree coverage (details to confirm)", "Cobertura del empleador o de jubilación (por confirmar)", "雇主或退休保障（細節待確認）", "雇主或退休保障（细节待确认）", "직장 또는 퇴직자 보장 (세부 확인 필요)"],
    "not_enrolled": ["Not yet enrolled in Medicare", "Aún no tengo Medicare", "尚未加入 Medicare", "尚未加入 Medicare", "아직 Medicare에 가입하지 않았어요"],
    "priority": ["What matters most right now?", "¿Qué es lo más importante ahora?", "目前最在意的是什麼？", "目前最在意的是什么？", "지금 가장 중요한 것은 무엇인가요?"],
    "lower_premium": ["Monthly costs", "Los gastos mensuales", "每月費用", "每月费用", "월 비용"],
    "lower_risk": ["Unexpected out-of-pocket costs", "Los gastos de bolsillo inesperados", "意外增加的自付費用", "意外增加的自付费用", "예상치 못한 본인 부담 비용"],
    "broad_network": ["Keeping doctors / access to care", "Conservar mis médicos / acceso a atención", "保留醫師與就醫便利性", "保留医生与就医便利性", "현재 의사와 의료 이용 유지"],
    "drug_cost": ["Prescription drug coverage", "La cobertura de medicamentos", "處方藥保障", "处方药保障", "처방약 보장"],
    "timing": ["Understanding when to enroll", "Entender cuándo inscribirme", "了解何時需要申請", "了解何时需要申请", "가입 시기 이해하기"],
    "details": ["Anything you would like us to consider?", "¿Qué desea que tengamos en cuenta?", "有沒有希望一併考慮的需求？", "有没有希望一并考虑的需求？", "함께 고려할 사항이 있나요?"],
    "notes": ["Optional: doctor access, medications, current coverage or questions. Share only what you feel comfortable sharing.", "Opcional: médicos, medicamentos, cobertura o preguntas. Comparta solo lo que desee.", "選填：就醫、用藥、現有保障或其他疑問。只需填寫您願意分享的內容。", "选填：就医、用药、现有保障或其他疑问。只需填写您愿意分享的内容。", "선택: 의사, 약, 현재 보장 또는 질문. 공유하고 싶은 내용만 적어 주세요."],
    "location": ["Where is the Medicare beneficiary located?", "¿Dónde vive la persona beneficiaria?", "Medicare 使用者目前住在哪裡？", "Medicare 使用者目前住在哪里？", "Medicare 이용자는 어디에 거주하나요?"],
    "zip": ["ZIP code (optional; leave blank if unsure)", "Código postal (opcional)", "郵遞區號（選填，不確定可留白）", "邮递区号（选填，不确定可留白）", "우편번호 (선택, 모르면 비워 두세요)"],
    "zip_error": ["Use a five-digit ZIP code, or leave it blank.", "Escriba cinco dígitos o déjelo en blanco.", "請填寫五位數郵遞區號，或先留白。", "请填写五位数邮递区号，或先留白。", "다섯 자리 숫자를 입력하거나 비워 두세요."],
    "check": ["Does this look right?", "¿Es correcto?", "一起確認一下", "一起确认一下", "내용을 확인해 주세요"],
    "generate": ["See directions to explore →", "Ver opciones para explorar →", "看看可以了解的方向 →", "看看可以了解的方向 →", "알아볼 방향 보기 →"],
    "ask": ["What would you like to understand?", "¿Qué le gustaría entender?", "您想了解什麼？", "您想了解什么？", "무엇이 궁금하신가요?"],
    "ask_hint": ["For example, a term, bill or letter. A short question is enough.", "Por ejemplo, un término, una factura o una carta. Basta una pregunta breve.", "例如信件、帳單或不懂的名詞，簡單寫下問題就好。", "例如信件、账单或不懂的名词，简单写下问题就好。", "용어, 청구서 또는 편지에 관해 짧게 질문해 주세요."],
    "send": ["Get guidance →", "Ver orientación →", "了解建議方向 →", "了解建议方向 →", "안내 보기 →"],
    "upload": ["Optional: attach an image of a letter or bill", "Opcional: adjuntar imagen de una carta o factura", "選填：附上信件或帳單圖片", "选填：附上信件或账单图片", "선택: 편지 또는 청구서 이미지 첨부"],
    "empty": ["Please enter a question or attach an image.", "Escriba una pregunta o adjunte una imagen.", "請先寫下問題或附上圖片。", "请先写下问题或附上图片。", "질문을 적거나 이미지를 첨부해 주세요."],
    "waiting": ["Preparing directions to explore…", "Preparando orientación…", "正在整理可以了解的方向…", "正在整理可以了解的方向…", "알아볼 방향을 정리하고 있어요…"],
    "failure": ["We couldn't prepare guidance just now. Your answers are saved; please try again, or contact SHIP below.", "No pudimos preparar la orientación. Sus respuestas siguen guardadas; inténtelo de nuevo o contacte con SHIP.", "目前無法產生建議，您的回答仍保留著。可以再試一次，或向下方 SHIP 諮詢。", "目前无法生成建议，您的回答仍保留着。可以再试一次，或向下方 SHIP 咨询。", "지금은 안내를 준비하지 못했어요. 답변은 보관됩니다. 다시 시도하거나 아래 SHIP에 문의하세요."],
    "summary": ["Directions to explore", "Opciones para explorar", "值得進一步了解的方向", "值得进一步了解的方向", "더 알아볼 방향"],
    "advice": ["This summary offers directions to discuss, not a decision to enroll or switch plans. Confirm individual circumstances with official sources or SHIP.", "Este resumen ofrece orientación para conversar, no una decisión de inscripción o cambio. Confirme su situación con fuentes oficiales o SHIP.", "此摘要提供了解與討論方向，並非投保或更換方案的決定。個別適用情況請向官方單位或 SHIP 確認。", "此摘要提供了解与讨论方向，并非投保或更换方案的决定。个别适用情况请向官方单位或 SHIP 确认。", "이 요약은 논의할 방향을 안내하며 가입 또는 변경 결정이 아닙니다. 개인별 적용 여부는 공식 기관이나 SHIP에 확인하세요."],
    "copy": ["Copy summary", "Copiar resumen", "複製摘要文字", "复制摘要文字", "요약 복사"],
    "copied": ["Copied — paste it to share with family or a counselor.", "Copiado: péguelo para compartirlo con su familia o asesor.", "已複製，可以貼給家人或顧問。", "已复制，可以贴给家人或顾问。", "복사했어요. 가족이나 상담사에게 붙여넣어 공유하세요."],
    "copy_fallback": ["If copying is unavailable, select the text below to copy it.", "Si no puede copiarlo, seleccione el texto de abajo.", "若無法直接複製，請長按或選取下方文字複製。", "若无法直接复制，请长按或选取下方文字复制。", "복사가 안 되면 아래 글을 길게 누르거나 선택해 복사하세요."],
    "share": ["Text to share / print", "Texto para compartir / imprimir", "轉貼文字／列印", "转贴文字／打印", "공유할 텍스트 / 인쇄"],
    "print": ["Print / save as PDF", "Imprimir / guardar PDF", "列印／另存 PDF", "打印／另存 PDF", "인쇄 / PDF 저장"],
    "feedback": ["Was this summary easy to understand? (Optional)", "¿Fue fácil entender el resumen? (Opcional)", "這份摘要是否清楚好懂？（選填）", "这份摘要是否清楚好懂？（选填）", "요약을 이해하기 쉬웠나요? (선택)"],
    "clear": ["Very clear", "Muy claro", "非常清楚", "非常清楚", "매우 명확해요"],
    "mostly": ["Mostly clear", "Bastante claro", "大致清楚", "大致清楚", "대체로 명확해요"],
    "confused": ["Still confusing", "Sigo con dudas", "依然困惑", "依然困惑", "아직 어려워요"],
    "difficulty": ["Which part was hardest? (Optional)", "¿Qué fue lo más difícil? (Opcional)", "哪個部分最困難？（選填）", "哪个部分最困难？（选填）", "어떤 부분이 가장 어려웠나요? (선택)"],
    "starting": ["Knowing where to start", "Saber por dónde empezar", "起步不知道選什麼", "起步不知道选什么", "시작할 항목 고르기"],
    "terms": ["Understanding the terms", "Entender los términos", "專有名詞不懂", "专有名词不懂", "용어 이해하기"],
    "results": ["Understanding the summary", "Entender el resumen", "結果看不懂", "结果看不懂", "결과 이해하기"],
    "ship_title": ["Need a second opinion?", "¿Desea una segunda opinión?", "想找真人再次確認？", "想找真人再次确认？", "상담사와 다시 확인하고 싶으신가요?"],
    "ship_note": ["A free local SHIP counselor can help you review your options. Feedback is optional.", "Un asesor local gratuito de SHIP puede ayudarle a revisar sus opciones. La opinión es opcional.", "當地免費的 SHIP 顧問可協助您檢視選項，不需要先填回饋。", "当地免费的 SHIP 顾问可协助您查看选项，不需要先填反馈。", "지역 SHIP 상담사가 무료로 선택지 검토를 도와드립니다. 의견 제출은 선택입니다."],
    "ship_link": ["Find a local SHIP counselor →", "Buscar un asesor local de SHIP →", "尋找當地 SHIP 顧問 →", "寻找当地 SHIP 顾问 →", "지역 SHIP 상담사 찾기 →"],
    "more": ["Other tools", "Otras herramientas", "其他工具", "其他工具", "기타 도구"],
    "prep": ["Prepare for a counselor conversation", "Preparar la consulta", "準備與顧問討論的資料", "准备与顾问讨论的资料", "상담 준비하기"],
    "restart": ["Start again", "Volver a empezar", "重新開始", "重新开始", "다시 시작"],
    "reset_note": ["This clears this person's answers and summary. Keep language and text size?", "Se borrarán las respuestas y el resumen. Se conservarán el idioma y el tamaño de texto.", "將清除這次的回答與摘要，並保留語言與字體設定。", "将清除这次的回答与摘要，并保留语言与字体设置。", "답변과 요약을 지우고 언어와 글자 크기는 유지합니다."],
    "confirm": ["Confirm restart", "Confirmar reinicio", "確認重新開始", "确认重新开始", "다시 시작 확인"],
    "about": ["About & trust", "Acerca de y confianza", "關於與免責", "关于与免责", "소개 및 안내"],
    "size": ["Text size", "Tamaño del texto", "閱讀字體", "阅读字体", "글자 크기"],
    "standard": ["A Standard", "A Estándar", "A 標準", "A 标准", "A 보통"],
    "large": ["A+ Large", "A+ Grande", "A+ 偏大", "A+ 偏大", "A+ 크게"],
    "largest": ["A++ Extra large", "A++ Muy grande", "A++ 特大", "A++ 特大", "A++ 아주 크게"],
    "year": ["Reference year: {year}", "Año de referencia: {year}", "資料參考年度：{year}", "资料参考年度：{year}", "자료 기준 연도: {year}"],
    "date": ["Content compiled: {date}", "Contenido recopilado: {date}", "內容整理日期：{date}", "内容整理日期：{date}", "내용 정리일: {date}"],
    "source": ["Based on official information referenced when this site was prepared; not a live update service. Confirm current rules with official sources or SHIP.", "Basado en información oficial consultada al preparar el sitio; no se actualiza en tiempo real. Confirme las normas vigentes con fuentes oficiales o SHIP.", "依網站建置時參考的官方資訊整理，非即時更新。最新規定請向官方單位或 SHIP 確認。", "依网站建置时参考的官方信息整理，非实时更新。最新规定请向官方单位或 SHIP 确认。", "사이트 제작 시 참고한 공식 정보를 정리했으며 실시간 업데이트가 아닙니다. 최신 규정은 공식 기관이나 SHIP에 확인하세요."],
    "neutral": ["Medicare Compass uses AI to help organize official information. We do not sell insurance or receive broker commissions.", "Medicare Compass utiliza IA para organizar información oficial. No vendemos seguros ni recibimos comisiones de intermediación.", "Medicare Compass 採用 AI 輔助技術整理官方資訊。我們不推銷任何保單，也不收取經紀人佣金。", "Medicare Compass 采用 AI 辅助技术整理官方信息。我们不推销任何保单，也不收取经纪人佣金。", "Medicare Compass는 AI로 공식 정보 정리를 돕습니다. 보험을 판매하거나 중개 수수료를 받지 않습니다."],
}


def text(language):
    index = LANGUAGES.index(language) if language in LANGUAGES else 0
    return {key: values[index] for key, values in ROWS.items()}
